/**
 * Auto-genera la lista de fotos de la galería del hub de mercados.
 *
 * Workflow para Dani:
 *   1. Drop your photos in: public/images/mercado/gallery/
 *   2. Run: npm run gallery   (o solo push — corre automático en cada build de Vercel)
 *   3. Done — la galería se actualiza sola
 *
 * Output: src/data/gallery-photos.ts
 * Soporta: .jpg, .jpeg, .png, .webp, .avif (case-insensitive)
 */

const fs = require('fs')
const path = require('path')

const PROJECT_ROOT = path.join(__dirname, '..')
const GALLERY_DIR = path.join(PROJECT_ROOT, 'public', 'images', 'mercado', 'gallery')
const OUTPUT_FILE = path.join(PROJECT_ROOT, 'src', 'data', 'gallery-photos.ts')

const IMAGE_EXTENSIONS = /\.(jpe?g|png|webp|avif)$/i

// Ensure gallery directory exists (no-op if it does)
fs.mkdirSync(GALLERY_DIR, { recursive: true })

// List image files, ignore hidden files and .DS_Store
const files = fs
  .readdirSync(GALLERY_DIR)
  .filter((f) => IMAGE_EXTENSIONS.test(f) && !f.startsWith('.'))
  // natural sort: image-2 before image-10
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }))

// Generate human-readable alt text from the filename
function generateAlt(filename) {
  const base = filename
    .replace(/\.[^.]+$/, '') // strip extension
    .replace(/[-_]+/g, ' ') // hyphens/underscores → spaces
    .replace(/\s+/g, ' ') // collapse whitespace
    .trim()

  // Skip purely numeric/junk filenames; fall back to a generic alt
  if (!base || /^(img|image|whatsapp|dsc|photo|foto)\b/i.test(base) || /^\d+$/.test(base)) {
    return 'Montaje del mercado en Casa de los Ángeles'
  }

  // Title-case the first letter of each word
  return base.replace(/\b\w/g, (c) => c.toUpperCase())
}

const photos = files.map((f) => ({
  src: `/images/mercado/gallery/${f}`,
  alt: generateAlt(f),
}))

// Build the TS file
const banner = `// AUTO-GENERATED by scripts/generate-gallery.js — do NOT edit manually.
// To update: drop photos in /public/images/mercado/gallery/ and the next build will refresh this file.
// Manual refresh: npm run gallery
`

const tsContent = `${banner}
export const GALLERY_PHOTOS: ReadonlyArray<{ src: string; alt: string }> = ${JSON.stringify(
  photos,
  null,
  2
)} as const
`

// Ensure output dir exists
fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf8')

const relativeOut = path.relative(PROJECT_ROOT, OUTPUT_FILE)
const count = photos.length
console.log(
  `\n✓ Gallery: ${count} image${count === 1 ? '' : 's'} detected${count === 0 ? ' (folder vacío — el sitio mostrará el placeholder)' : ''}`
)
files.forEach((f) => console.log(`  · ${f}`))
console.log(`→ Written to ${relativeOut}\n`)
