// AUTO-GENERATED by scripts/generate-gallery.js — do NOT edit manually.
// To update: drop photos in /public/images/mercado/gallery/ and the next build will refresh this file.
// Manual refresh: npm run gallery

export const GALLERY_PHOTOS: ReadonlyArray<{ src: string; alt: string }> = [] as const
